### ISSUE TITLE
[Question](How) to handle unsupported icons

### ISSUE THREAD

**Issue by MiepHD** [zixpo/candybar#175]
How can I configure how icons that aren't supported from the iconpack should look like?
In the launcher I use the unsupported icons get smaller which doesn't match the supported icons.
![WhatsApp Bild 2024-02-11 um 09 05 12_83251ab4](https://github.com/zixpo/candybar/assets/63968466/45563732-5ce9-4d0d-b838-380dd7cf37a1)
![WhatsApp Bild 2024-02-11 um 09 05 12_5bc1e2e4](https://github.com/zixpo/candybar/assets/63968466/b22aa5f7-0841-40fc-8cd5-1ea82ec4214a)
In Kiss Launcher the icons turn completely white
https://github.com/MiepHD/cuscon/issues/18
![](https://private-user-images.githubusercontent.com/4341884/303859705-b846675c-2505-4372-ad50-ec545d4866f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTMzNDMsIm5iZiI6MTcwNzgxMzA0MywicGF0aCI6Ii80MzQxODg0LzMwMzg1OTcwNS1iODQ2Njc1Yy0yNTA1LTQzNzItYWQ1MC1lYzU0NWQ0ODY2ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMDgzMDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk0Y2E3ZGU2OTBmZGU3MTBkODU3MDEzNzllNGU0MDFiNzA4YTdmMDAzZmJmNmU4ZmI2OTUwOGEwYmJjYzFjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mPm2hzgD4it4ms9VK6xHci7XKLwHK-qWxaUHETqmNpo)

**Comment by jm355** [comment]
One difference I notice between cuscon and arcticons is that arcticons does not have an appmap.xml or theme_resources.xml. Maybe cuscon doesn't need those either?

**Comment by Donnnno** [comment]
I've never had any complaints about the appmap and theme resources missing.

But then again, idk what they do

**Comment by kshitijdeota** [comment]
@MiepHD Use `<scale factor="x.xx" />` (0.01 ~ 1.00) given in "appfilter.xml", not all launchers respect the icon size settings though.

@Donnnno 
appmap.xml was provided for launchers like "arrow launcher", "yahoo launcher" and some others that no longer exist. I bet it was abandoned because the xml does not list package names with app activities but just the package names which isn't very helpful today.

theme_resources.xml is for "LG Home", LG phones and their stock launcher used to be really popular back then. I do have enough LG users even today and few launchers still take advantage of this file. It's good to have it in your icon pack.

appfilter.xml has been widely used by most launchers since Nova/ADW/Apex days so it has become an unofficial standard these days for every new launcher.

All the three xml files can be turned on/off form `CandyBar.java`. App won't generate turned off xml files during icon request. Read the onInit() settings here [CandyBar.java](https://github.com/zixpo/candybar-sample/blob/main/app/src/main/java/com/candybar/sample/applications/CandyBar.java)

Turned off xml files can also be cleaned up (deleted from the app).

**Comment by Donnnno** [comment]
Thanks for the explanation @kshitijdeota !

**Comment by MiepHD** [comment]
Thanks, the unsupported icons will now display in the right size. Only question remaining why do the unsupported icons turn white in Kiss Launcher?

**Comment by kshitijdeota** [comment]
Remove iconback, iconmask and iconupon references in your appfilter.xml. That should possibly fix the issue.

**Comment by MiepHD** [comment]
Thanks 😅 Works perfect
