### ISSUE TITLE
New build Version crashed

### ISSUE THREAD

**Issue by atanusanyal** [zixpo/candybar#49]
![Screenshot_2021-08-07-00-47-14-912_com atanusanyal eight](https://user-images.githubusercontent.com/7301670/128561072-d00348d9-dd65-40f4-b038-9f84bc5035c1.jpg)

**Comment by sarsamurmu** [comment]
I don't think changing the version code or version number would cause a crash. Please check that you didn't do something wrong.

**Comment by kshitijdeota** [comment]
Facing the same crash issue on tapping "Icon Request" over Android 4.4.2

Here is the crash log

Icon Pack Name : CandyBar Sample
Manufacturer : asus
Model : ASUS_Z007
Product : WW_zc451cg
Screen Resolution : 480 x 854 pixels
Android Version : 4.4.2
App Version : 1.0
CandyBar Version : 3.12.0
Crash Time : 2021-08-10 01:36:56
Class Name : android.content.res.Resources$NotFoundException
Caused By : android.content.res.Resources$NotFoundException: File res/drawable/ic_fab_send.xml from drawable resource ID #0x7f080080. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.

android.content.res.Resources.loadDrawable(Resources.java:2156)
android.content.res.Resources.loadDrawable(Resources.java:2075)
android.content.res.Resources.getDrawable(Resources.java:706)
androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:97)
candybar.lib.fragments.RequestFragment.onViewCreated(RequestFragment.java:139)
androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
android.os.Handler.handleCallback(Handler.java:733)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:149)
android.app.ActivityThread.main(ActivityThread.java:5268)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
dalvik.system.NativeStart.main(Native Method)

**Comment by kshitijdeota** [comment]
For a temporary fix I include the file "https://github.com/zixpo/candybar/blob/main/library/src/main/res/drawable/ic_fab_send.xml"
 in the drawable folder and it solves the problem. I suspect it's just some file encoding issue in the actual included library

**Comment by benasdzimidas** [comment]
I acknowledge that this is not the solution, but it would be rational to drop Android version that is 8 years old, @kshitijdeota.
