### ISSUE TITLE
Pressing on clock widget opens icon pack instead of clock app

### ISSUE THREAD

**Issue by wokija** [zixpo/candybar#81]
Updated to latest CandyBar version (v.3.14.1) before pushing icon pack release to play store. Received a bug report this morning stating that Clock widget now points to the icon pack app instead of the clock app like it used to be.

Tested with last release and it does indeed open the clock app.

**Comment by Donnnno** [comment]
it opens the icon pack for me, and others as well :s

**Comment by basings** [comment]
on my device clicking it does nothing at all, not even opening the icon pack

**Comment by moertel** [comment]
On my device (Samsung G22 Ultra) tapping the analog clock does nothing either. Instead of getting tied to a specific app (which I believe is tough because the package names differ depending on device brand) I'd prefer to open a dialog for the user to choose an app.

I'm happy to contribute it. Let me know what you think!

**Comment by Donnnno** [comment]
https://github.com/Donnnno/candybar-foss/pull/6 the fix!

**Comment by sarsamurmu** [comment]
Cool!
